### ISSUE TITLE
Use the right AZs when a region is passed in

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#56]
Right now if a --region is passed, we still use a hardcoded list, meaning when we provision everything breaks.  Not cool.

This is going to need to tie in later when we start auto grabbing the right ubuntu AMI for an AZ (and virtualization type) as well so that should be considered.

**Comment by rustyrazorblade** [comment]
Implementation wise, this is all going to be yaml driven.  This relates to #58, since the amis are driven by region and instance type.  I think we'll be looking at a yaml like this:

```yaml
--- 
regions: 
  us-west-2: 
    amis: 
      ebs: ami-0013ea6a76d3b8874
      instance: ami-0fdf0d5b47d0cba88
    azs: 
      - us-west-a
      - us-west-b
      - us-west-c
```
